version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile
        #image: php:8.1-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            #DATABASE_URL: "postgres://fl0user:0wYvtHL4fzsZ@ep-spring-hall-35501515.eu-central-1.aws.neon.tech:5432/modattire-bd?sslmode=require"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
