version: 2.1
jobs:
  build:
    docker:
      - image: php:8.1
    steps:
      - checkout
      # install docker-compose
      - run:
          name: Install Composer Dependencies
          command: composer install