version: 2.1
jobs:
  build:
    docker:
      - image: php:8.1
    steps:
      - checkout
      # Ejecuta el servidor PHP local
      - run:
          name: Run PHP Development Server
          command: nohup php -S 0.0.0.0:8080 -t public > /dev/null 2>&1 &
